#pragma once

#include <cstdint>

#include "nyla/commons/macros.h"

namespace nyla
{

enum class input_interface_type : uint8_t
{
    Keyboard,
    Mouse,
    Gamepad,
};

enum class input_id : uint8_t
{
    None = 0,

    // 1..31 : movement
    MoveForward = 1,
    MoveBackward,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    Jump,
    Crouch,
    Prone,
    Sprint,
    Walk,
    Dash,
    Dodge,
    Roll,
    Slide,
    Vault,
    Mantle,
    Climb,
    Descend,
    SwimUp,
    SwimDown,
    FlyUp,
    FlyDown,
    Hover,
    Glide,
    LeanLeft,
    LeanRight,
    PeekLeft,
    PeekRight,
    StrafeModifier,
    AutoRun,

    // 32..63 : camera / look
    LookUp,
    LookDown,
    LookLeft,
    LookRight,
    TurnLeft,
    TurnRight,
    TurnUp,
    TurnDown,
    CameraZoomIn,
    CameraZoomOut,
    CameraReset,
    CameraModeNext,
    CameraModePrev,
    CameraOrbit,
    CameraFreeLook,
    CameraCenter,
    CameraLock,
    CameraUnlock,
    CameraPanUp,
    CameraPanDown,
    CameraPanLeft,
    CameraPanRight,
    CameraTiltUp,
    CameraTiltDown,
    CameraRotateLeft,
    CameraRotateRight,
    CameraDistanceNear,
    CameraDistanceFar,
    CameraShoulderLeft,
    CameraShoulderRight,
    TargetLook,
    PhotoMode,

    // 64..95 : combat
    AttackPrimary,
    AttackSecondary,
    AttackTertiary,
    AttackQuaternary,
    LightAttack,
    HeavyAttack,
    ChargedAttack,
    ComboAttack,
    SpecialAttack,
    Block,
    Parry,
    GuardBreak,
    Riposte,
    Aim,
    HipFire,
    Reload,
    Chamber,
    FireModeNext,
    FireModePrev,
    WeaponSafety,
    Melee,
    Execute,
    Finisher,
    ThrowGrenade,
    ThrowAlt,
    Detonate,
    UseGadget,
    GadgetNext,
    GadgetPrev,
    LockTarget,
    TargetNext,
    TargetPrev,

    // 96..127 : abilities / items
    Ability1,
    Ability2,
    Ability3,
    Ability4,
    Ability5,
    Ability6,
    Ability7,
    Ability8,
    Ultimate,
    SkillTree,
    Cast,
    Channel,
    ChargeAbility,
    CancelAbility,
    ItemUse,
    ItemAltUse,
    ItemDrop,
    ItemPickup,
    ItemInspect,
    ItemHolster,
    ItemUnholster,
    NextItem,
    PrevItem,
    NextWeapon,
    PrevWeapon,
    WeaponSlot1,
    WeaponSlot2,
    WeaponSlot3,
    WeaponSlot4,
    WeaponSlot5,
    WeaponSlot6,
    WeaponSlot7,

    // 128..159 : inventory / ui
    WeaponSlot8,
    WeaponSlot9,
    WeaponSlot10,
    Inventory,
    Map,
    Journal,
    QuestLog,
    Character,
    Skills,
    Crafting,
    BuildMenu,
    RadialMenu,
    Scoreboard,
    Objectives,
    Ping,
    Emote,
    Spray,
    Chat,
    VoicePushToTalk,
    VoiceMuteToggle,
    TextCursorAccept,
    TextCursorCancel,
    Menu,
    Pause,
    Confirm,
    Cancel,
    Back,
    TabLeft,
    TabRight,
    PageLeft,
    PageRight,
    ContextMenu,

    // 160..191 : interaction / system
    Interact,
    Use,
    UseSecondary,
    UseTertiary,
    Open,
    Close,
    Toggle,
    Activate,
    Deactivate,
    Grab,
    Release,
    Push,
    Pull,
    Carry,
    Drop,
    Throw,
    Place,
    Remove,
    RotateCW,
    RotateCCW,
    Copy,
    Paste,
    Duplicate,
    Undo,
    Redo,
    Delete,
    Reset,
    Start,
    Select,
    Help,
    Screenshot,
    RecordClip,

    // 192..223 : meta / debug / match / vehicle
    ToggleHUD,
    ToggleConsole,
    ToggleDebug,
    ToggleMapOverlay,
    QuickSave,
    QuickLoad,
    Save,
    Load,
    Respawn,
    SpectateNext,
    SpectatePrev,
    ReadyToggle,
    VoteYes,
    VoteNo,
    Accelerate,
    Brake,
    BrakeAlt,
    Handbrake,
    SteerLeft,
    SteerRight,
    PitchUp,
    PitchDown,
    YawLeft,
    YawRight,
    RollLeft,
    RollRight,
    GearUp,
    GearDown,
    Horn,
    LightsToggle,
    WipersToggle,
    VehicleLookBack,

    // 224..255 : vehicle extras + generic expansion
    VehicleCameraMode,
    ExitVehicle,
    Mount,
    Dismount,
    SailTrimIn,
    SailTrimOut,
    AnchorToggle,
    LandingGearToggle,
    AutoPilotToggle,
    Aux1,
    Aux2,
    Aux3,
    Aux4,
    Aux5,
    Aux6,
    Aux7,
    Aux8,
    Custom1,
    Custom2,
    Custom3,
    Custom4,
    Custom5,
    Custom6,
    Custom7,
    Custom8,
    Custom9,
    Custom10,
    Custom11,
    Custom12,
    Custom13,
    Custom14,
    Custom15,
};

namespace InputManager
{

void API Update();

void API Map(uint32_t inputId, input_interface_type type, uint32_t code);
auto API IsPressed(uint32_t input) -> bool;

void API HandlePressed(input_interface_type type, uint32_t code, uint64_t time);
void API HandleReleased(input_interface_type type, uint32_t code, uint64_t time);

} // namespace InputManager

} // namespace nyla