#include "nyla/commons/spv_shader.h"
#include "nyla/commons/spv_reader.h"

namespace nyla
{

namespace SpvShader
{

enum class spv_decoration
{
    RelaxedPrecision = 0,
    SpecId = 1,
    Block = 2,
    BufferBlock = 3,
    RowMajor = 4,
    ColMajor = 5,
    ArrayStride = 6,
    MatrixStride = 7,
    GLSLShared = 8,
    GLSLPacked = 9,
    CPacked = 10,
    BuiltIn = 11,
    NoPerspective = 13,
    Flat = 14,
    Patch = 15,
    Centroid = 16,
    Sample = 17,
    Invariant = 18,
    Restrict = 19,
    Aliased = 20,
    Volatile = 21,
    Constant = 22,
    Coherent = 23,
    NonWritable = 24,
    NonReadable = 25,
    Uniform = 26,
    UniformId = 27,
    SaturatedConversion = 28,
    Stream = 29,
    Location = 30,
    Component = 31,
    Index = 32,
    Binding = 33,
    DescriptorSet = 34,
    Offset = 35,
    XfbBuffer = 36,
    XfbStride = 37,
    FuncParamAttr = 38,
    FPRoundingMode = 39,
    FPFastMathMode = 40,
    LinkageAttributes = 41,
    NoContraction = 42,
    InputAttachmentIndex = 43,
    Alignment = 44,
    MaxByteOffset = 45,
    AlignmentId = 46,
    MaxByteOffsetId = 47,
    SaturatedToLargestFloat8NormalConversionEXT = 4216,
    NoSignedWrap = 4469,
    NoUnsignedWrap = 4470,
    WeightTextureQCOM = 4487,
    BlockMatchTextureQCOM = 4488,
    BlockMatchSamplerQCOM = 4499,
    ExplicitInterpAMD = 4999,
    NodeSharesPayloadLimitsWithAMDX = 5019,
    NodeMaxPayloadsAMDX = 5020,
    TrackFinishWritingAMDX = 5078,
    PayloadNodeNameAMDX = 5091,
    PayloadNodeBaseIndexAMDX = 5098,
    PayloadNodeSparseArrayAMDX = 5099,
    PayloadNodeArraySizeAMDX = 5100,
    PayloadDispatchIndirectAMDX = 5105,
    ArrayStrideIdEXT = 5124,
    OffsetIdEXT = 5125,
    OverrideCoverageNV = 5248,
    PassthroughNV = 5250,
    ViewportRelativeNV = 5252,
    SecondaryViewportRelativeNV = 5256,
    PerPrimitiveEXT = 5271,
    PerPrimitiveNV = 5271,
    PerViewNV = 5272,
    PerTaskNV = 5273,
    PerVertexKHR = 5285,
    PerVertexNV = 5285,
    NonUniform = 5300,
    NonUniformEXT = 5300,
    RestrictPointer = 5355,
    RestrictPointerEXT = 5355,
    AliasedPointer = 5356,
    AliasedPointerEXT = 5356,
    MemberOffsetNV = 5358,
    HitObjectShaderRecordBufferNV = 5386,
    HitObjectShaderRecordBufferEXT = 5389,
    BankNV = 5397,
    BindlessSamplerNV = 5398,
    BindlessImageNV = 5399,
    BoundSamplerNV = 5400,
    BoundImageNV = 5401,
    SIMTCallINTEL = 5599,
    ReferencedIndirectlyINTEL = 5602,
    ClobberINTEL = 5607,
    SideEffectsINTEL = 5608,
    VectorComputeVariableINTEL = 5624,
    FuncParamIOKindINTEL = 5625,
    VectorComputeFunctionINTEL = 5626,
    StackCallINTEL = 5627,
    GlobalVariableOffsetINTEL = 5628,
    CounterBuffer = 5634,
    HlslCounterBufferGOOGLE = 5634,
    HlslSemanticGOOGLE = 5635,
    UserSemantic = 5635,
    UserTypeGOOGLE = 5636,
    FunctionRoundingModeINTEL = 5822,
    FunctionDenormModeINTEL = 5823,
    RegisterALTERA = 5825,
    RegisterINTEL = 5825,
    MemoryALTERA = 5826,
    MemoryINTEL = 5826,
    NumbanksALTERA = 5827,
    NumbanksINTEL = 5827,
    BankwidthALTERA = 5828,
    BankwidthINTEL = 5828,
    MaxPrivateCopiesALTERA = 5829,
    MaxPrivateCopiesINTEL = 5829,
    SinglepumpALTERA = 5830,
    SinglepumpINTEL = 5830,
    DoublepumpALTERA = 5831,
    DoublepumpINTEL = 5831,
    MaxReplicatesALTERA = 5832,
    MaxReplicatesINTEL = 5832,
    SimpleDualPortALTERA = 5833,
    SimpleDualPortINTEL = 5833,
    MergeALTERA = 5834,
    MergeINTEL = 5834,
    BankBitsALTERA = 5835,
    BankBitsINTEL = 5835,
    ForcePow2DepthALTERA = 5836,
    ForcePow2DepthINTEL = 5836,
    StridesizeALTERA = 5883,
    StridesizeINTEL = 5883,
    WordsizeALTERA = 5884,
    WordsizeINTEL = 5884,
    TrueDualPortALTERA = 5885,
    TrueDualPortINTEL = 5885,
    BurstCoalesceALTERA = 5899,
    BurstCoalesceINTEL = 5899,
    CacheSizeALTERA = 5900,
    CacheSizeINTEL = 5900,
    DontStaticallyCoalesceALTERA = 5901,
    DontStaticallyCoalesceINTEL = 5901,
    PrefetchALTERA = 5902,
    PrefetchINTEL = 5902,
    StallEnableALTERA = 5905,
    StallEnableINTEL = 5905,
    FuseLoopsInFunctionALTERA = 5907,
    FuseLoopsInFunctionINTEL = 5907,
    MathOpDSPModeALTERA = 5909,
    MathOpDSPModeINTEL = 5909,
    AliasScopeINTEL = 5914,
    NoAliasINTEL = 5915,
    InitiationIntervalALTERA = 5917,
    InitiationIntervalINTEL = 5917,
    MaxConcurrencyALTERA = 5918,
    MaxConcurrencyINTEL = 5918,
    PipelineEnableALTERA = 5919,
    PipelineEnableINTEL = 5919,
    BufferLocationALTERA = 5921,
    BufferLocationINTEL = 5921,
    IOPipeStorageALTERA = 5944,
    IOPipeStorageINTEL = 5944,
    FunctionFloatingPointModeINTEL = 6080,
    SingleElementVectorINTEL = 6085,
    VectorComputeCallableFunctionINTEL = 6087,
    MediaBlockIOINTEL = 6140,
    StallFreeALTERA = 6151,
    StallFreeINTEL = 6151,
    FPMaxErrorDecorationINTEL = 6170,
    LatencyControlLabelALTERA = 6172,
    LatencyControlLabelINTEL = 6172,
    LatencyControlConstraintALTERA = 6173,
    LatencyControlConstraintINTEL = 6173,
    ConduitKernelArgumentALTERA = 6175,
    ConduitKernelArgumentINTEL = 6175,
    RegisterMapKernelArgumentALTERA = 6176,
    RegisterMapKernelArgumentINTEL = 6176,
    MMHostInterfaceAddressWidthALTERA = 6177,
    MMHostInterfaceAddressWidthINTEL = 6177,
    MMHostInterfaceDataWidthALTERA = 6178,
    MMHostInterfaceDataWidthINTEL = 6178,
    MMHostInterfaceLatencyALTERA = 6179,
    MMHostInterfaceLatencyINTEL = 6179,
    MMHostInterfaceReadWriteModeALTERA = 6180,
    MMHostInterfaceReadWriteModeINTEL = 6180,
    MMHostInterfaceMaxBurstALTERA = 6181,
    MMHostInterfaceMaxBurstINTEL = 6181,
    MMHostInterfaceWaitRequestALTERA = 6182,
    MMHostInterfaceWaitRequestINTEL = 6182,
    StableKernelArgumentALTERA = 6183,
    StableKernelArgumentINTEL = 6183,
    HostAccessINTEL = 6188,
    InitModeALTERA = 6190,
    InitModeINTEL = 6190,
    ImplementInRegisterMapALTERA = 6191,
    ImplementInRegisterMapINTEL = 6191,
    ConditionalINTEL = 6247,
    CacheControlLoadINTEL = 6442,
    CacheControlStoreINTEL = 6443,
    Max = 0x7fffffff,
};

enum class spv_execution_model
{
    Vertex = 0,
    TessellationControl = 1,
    TessellationEvaluation = 2,
    Geometry = 3,
    Fragment = 4,
    GLCompute = 5,
    Kernel = 6,
    TaskNV = 5267,
    MeshNV = 5268,
    RayGenerationKHR = 5313,
    RayGenerationNV = 5313,
    IntersectionKHR = 5314,
    IntersectionNV = 5314,
    AnyHitKHR = 5315,
    AnyHitNV = 5315,
    ClosestHitKHR = 5316,
    ClosestHitNV = 5316,
    MissKHR = 5317,
    MissNV = 5317,
    CallableKHR = 5318,
    CallableNV = 5318,
    TaskEXT = 5364,
    MeshEXT = 5365,
    Max = 0x7fffffff,
};

enum class spv_storage_class
{
    UniformConstant = 0,
    Input = 1,
    Uniform = 2,
    Output = 3,
    Workgroup = 4,
    CrossWorkgroup = 5,
    Private = 6,
    Function = 7,
    Generic = 8,
    PushConstant = 9,
    AtomicCounter = 10,
    Image = 11,
    StorageBuffer = 12,
    TileImageEXT = 4172,
    TileAttachmentQCOM = 4491,
    NodePayloadAMDX = 5068,
    CallableDataKHR = 5328,
    CallableDataNV = 5328,
    IncomingCallableDataKHR = 5329,
    IncomingCallableDataNV = 5329,
    RayPayloadKHR = 5338,
    RayPayloadNV = 5338,
    HitAttributeKHR = 5339,
    HitAttributeNV = 5339,
    IncomingRayPayloadKHR = 5342,
    IncomingRayPayloadNV = 5342,
    ShaderRecordBufferKHR = 5343,
    ShaderRecordBufferNV = 5343,
    PhysicalStorageBuffer = 5349,
    PhysicalStorageBufferEXT = 5349,
    HitObjectAttributeNV = 5385,
    TaskPayloadWorkgroupEXT = 5402,
    HitObjectAttributeEXT = 5411,
    CodeSectionINTEL = 5605,
    DeviceOnlyALTERA = 5936,
    DeviceOnlyINTEL = 5936,
    HostOnlyALTERA = 5937,
    HostOnlyINTEL = 5937,
    Max = 0x7fffffff,
};

enum class spv_op
{
    Nop = 0,
    Undef = 1,
    SourceContinued = 2,
    Source = 3,
    SourceExtension = 4,
    Name = 5,
    MemberName = 6,
    String = 7,
    Line = 8,
    Extension = 10,
    ExtInstImport = 11,
    ExtInst = 12,
    MemoryModel = 14,
    EntryPoint = 15,
    ExecutionMode = 16,
    Capability = 17,
    TypeVoid = 19,
    TypeBool = 20,
    TypeInt = 21,
    TypeFloat = 22,
    TypeVector = 23,
    TypeMatrix = 24,
    TypeImage = 25,
    TypeSampler = 26,
    TypeSampledImage = 27,
    TypeArray = 28,
    TypeRuntimeArray = 29,
    TypeStruct = 30,
    TypeOpaque = 31,
    TypePointer = 32,
    TypeFunction = 33,
    TypeEvent = 34,
    TypeDeviceEvent = 35,
    TypeReserveId = 36,
    TypeQueue = 37,
    TypePipe = 38,
    TypeForwardPointer = 39,
    ConstantTrue = 41,
    ConstantFalse = 42,
    Constant = 43,
    ConstantComposite = 44,
    ConstantSampler = 45,
    ConstantNull = 46,
    SpecConstantTrue = 48,
    SpecConstantFalse = 49,
    SpecConstant = 50,
    SpecConstantComposite = 51,
    SpecConstantOp = 52,
    Function = 54,
    FunctionParameter = 55,
    FunctionEnd = 56,
    FunctionCall = 57,
    Variable = 59,
    ImageTexelPointer = 60,
    Load = 61,
    Store = 62,
    CopyMemory = 63,
    CopyMemorySized = 64,
    AccessChain = 65,
    InBoundsAccessChain = 66,
    PtrAccessChain = 67,
    ArrayLength = 68,
    GenericPtrMemSemantics = 69,
    InBoundsPtrAccessChain = 70,
    Decorate = 71,
    MemberDecorate = 72,
    DecorationGroup = 73,
    GroupDecorate = 74,
    GroupMemberDecorate = 75,
    VectorExtractDynamic = 77,
    VectorInsertDynamic = 78,
    VectorShuffle = 79,
    CompositeConstruct = 80,
    CompositeExtract = 81,
    CompositeInsert = 82,
    CopyObject = 83,
    Transpose = 84,
    SampledImage = 86,
    ImageSampleImplicitLod = 87,
    ImageSampleExplicitLod = 88,
    ImageSampleDrefImplicitLod = 89,
    ImageSampleDrefExplicitLod = 90,
    ImageSampleProjImplicitLod = 91,
    ImageSampleProjExplicitLod = 92,
    ImageSampleProjDrefImplicitLod = 93,
    ImageSampleProjDrefExplicitLod = 94,
    ImageFetch = 95,
    ImageGather = 96,
    ImageDrefGather = 97,
    ImageRead = 98,
    ImageWrite = 99,
    Image = 100,
    ImageQueryFormat = 101,
    ImageQueryOrder = 102,
    ImageQuerySizeLod = 103,
    ImageQuerySize = 104,
    ImageQueryLod = 105,
    ImageQueryLevels = 106,
    ImageQuerySamples = 107,
    ConvertFToU = 109,
    ConvertFToS = 110,
    ConvertSToF = 111,
    ConvertUToF = 112,
    UConvert = 113,
    SConvert = 114,
    FConvert = 115,
    QuantizeToF16 = 116,
    ConvertPtrToU = 117,
    SatConvertSToU = 118,
    SatConvertUToS = 119,
    ConvertUToPtr = 120,
    PtrCastToGeneric = 121,
    GenericCastToPtr = 122,
    GenericCastToPtrExplicit = 123,
    Bitcast = 124,
    SNegate = 126,
    FNegate = 127,
    IAdd = 128,
    FAdd = 129,
    ISub = 130,
    FSub = 131,
    IMul = 132,
    FMul = 133,
    UDiv = 134,
    SDiv = 135,
    FDiv = 136,
    UMod = 137,
    SRem = 138,
    SMod = 139,
    FRem = 140,
    FMod = 141,
    VectorTimesScalar = 142,
    MatrixTimesScalar = 143,
    VectorTimesMatrix = 144,
    MatrixTimesVector = 145,
    MatrixTimesMatrix = 146,
    OuterProduct = 147,
    Dot = 148,
    IAddCarry = 149,
    ISubBorrow = 150,
    UMulExtended = 151,
    SMulExtended = 152,
    Any = 154,
    All = 155,
    IsNan = 156,
    IsInf = 157,
    IsFinite = 158,
    IsNormal = 159,
    SignBitSet = 160,
    LessOrGreater = 161,
    Ordered = 162,
    Unordered = 163,
    LogicalEqual = 164,
    LogicalNotEqual = 165,
    LogicalOr = 166,
    LogicalAnd = 167,
    LogicalNot = 168,
    Select = 169,
    IEqual = 170,
    INotEqual = 171,
    UGreaterThan = 172,
    SGreaterThan = 173,
    UGreaterThanEqual = 174,
    SGreaterThanEqual = 175,
    ULessThan = 176,
    SLessThan = 177,
    ULessThanEqual = 178,
    SLessThanEqual = 179,
    FOrdEqual = 180,
    FUnordEqual = 181,
    FOrdNotEqual = 182,
    FUnordNotEqual = 183,
    FOrdLessThan = 184,
    FUnordLessThan = 185,
    FOrdGreaterThan = 186,
    FUnordGreaterThan = 187,
    FOrdLessThanEqual = 188,
    FUnordLessThanEqual = 189,
    FOrdGreaterThanEqual = 190,
    FUnordGreaterThanEqual = 191,
    ShiftRightLogical = 194,
    ShiftRightArithmetic = 195,
    ShiftLeftLogical = 196,
    BitwiseOr = 197,
    BitwiseXor = 198,
    BitwiseAnd = 199,
    Not = 200,
    BitFieldInsert = 201,
    BitFieldSExtract = 202,
    BitFieldUExtract = 203,
    BitReverse = 204,
    BitCount = 205,
    DPdx = 207,
    DPdy = 208,
    Fwidth = 209,
    DPdxFine = 210,
    DPdyFine = 211,
    FwidthFine = 212,
    DPdxCoarse = 213,
    DPdyCoarse = 214,
    FwidthCoarse = 215,
    EmitVertex = 218,
    EndPrimitive = 219,
    EmitStreamVertex = 220,
    EndStreamPrimitive = 221,
    ControlBarrier = 224,
    MemoryBarrier = 225,
    AtomicLoad = 227,
    AtomicStore = 228,
    AtomicExchange = 229,
    AtomicCompareExchange = 230,
    AtomicCompareExchangeWeak = 231,
    AtomicIIncrement = 232,
    AtomicIDecrement = 233,
    AtomicIAdd = 234,
    AtomicISub = 235,
    AtomicSMin = 236,
    AtomicUMin = 237,
    AtomicSMax = 238,
    AtomicUMax = 239,
    AtomicAnd = 240,
    AtomicOr = 241,
    AtomicXor = 242,
    Phi = 245,
    LoopMerge = 246,
    SelectionMerge = 247,
    Label = 248,
    Branch = 249,
    BranchConditional = 250,
    Switch = 251,
    Kill = 252,
    Return = 253,
    ReturnValue = 254,
    Unreachable = 255,
    LifetimeStart = 256,
    LifetimeStop = 257,
    GroupAsyncCopy = 259,
    GroupWaitEvents = 260,
    GroupAll = 261,
    GroupAny = 262,
    GroupBroadcast = 263,
    GroupIAdd = 264,
    GroupFAdd = 265,
    GroupFMin = 266,
    GroupUMin = 267,
    GroupSMin = 268,
    GroupFMax = 269,
    GroupUMax = 270,
    GroupSMax = 271,
    ReadPipe = 274,
    WritePipe = 275,
    ReservedReadPipe = 276,
    ReservedWritePipe = 277,
    ReserveReadPipePackets = 278,
    ReserveWritePipePackets = 279,
    CommitReadPipe = 280,
    CommitWritePipe = 281,
    IsValidReserveId = 282,
    GetNumPipePackets = 283,
    GetMaxPipePackets = 284,
    GroupReserveReadPipePackets = 285,
    GroupReserveWritePipePackets = 286,
    GroupCommitReadPipe = 287,
    GroupCommitWritePipe = 288,
    EnqueueMarker = 291,
    EnqueueKernel = 292,
    GetKernelNDrangeSubGroupCount = 293,
    GetKernelNDrangeMaxSubGroupSize = 294,
    GetKernelWorkGroupSize = 295,
    GetKernelPreferredWorkGroupSizeMultiple = 296,
    RetainEvent = 297,
    ReleaseEvent = 298,
    CreateUserEvent = 299,
    IsValidEvent = 300,
    SetUserEventStatus = 301,
    CaptureEventProfilingInfo = 302,
    GetDefaultQueue = 303,
    BuildNDRange = 304,
    ImageSparseSampleImplicitLod = 305,
    ImageSparseSampleExplicitLod = 306,
    ImageSparseSampleDrefImplicitLod = 307,
    ImageSparseSampleDrefExplicitLod = 308,
    ImageSparseSampleProjImplicitLod = 309,
    ImageSparseSampleProjExplicitLod = 310,
    ImageSparseSampleProjDrefImplicitLod = 311,
    ImageSparseSampleProjDrefExplicitLod = 312,
    ImageSparseFetch = 313,
    ImageSparseGather = 314,
    ImageSparseDrefGather = 315,
    ImageSparseTexelsResident = 316,
    NoLine = 317,
    AtomicFlagTestAndSet = 318,
    AtomicFlagClear = 319,
    ImageSparseRead = 320,
    SizeOf = 321,
    TypePipeStorage = 322,
    ConstantPipeStorage = 323,
    CreatePipeFromPipeStorage = 324,
    GetKernelLocalSizeForSubgroupCount = 325,
    GetKernelMaxNumSubgroups = 326,
    TypeNamedBarrier = 327,
    NamedBarrierInitialize = 328,
    MemoryNamedBarrier = 329,
    ModuleProcessed = 330,
    ExecutionModeId = 331,
    DecorateId = 332,
    GroupNonUniformElect = 333,
    GroupNonUniformAll = 334,
    GroupNonUniformAny = 335,
    GroupNonUniformAllEqual = 336,
    GroupNonUniformBroadcast = 337,
    GroupNonUniformBroadcastFirst = 338,
    GroupNonUniformBallot = 339,
    GroupNonUniformInverseBallot = 340,
    GroupNonUniformBallotBitExtract = 341,
    GroupNonUniformBallotBitCount = 342,
    GroupNonUniformBallotFindLSB = 343,
    GroupNonUniformBallotFindMSB = 344,
    GroupNonUniformShuffle = 345,
    GroupNonUniformShuffleXor = 346,
    GroupNonUniformShuffleUp = 347,
    GroupNonUniformShuffleDown = 348,
    GroupNonUniformIAdd = 349,
    GroupNonUniformFAdd = 350,
    GroupNonUniformIMul = 351,
    GroupNonUniformFMul = 352,
    GroupNonUniformSMin = 353,
    GroupNonUniformUMin = 354,
    GroupNonUniformFMin = 355,
    GroupNonUniformSMax = 356,
    GroupNonUniformUMax = 357,
    GroupNonUniformFMax = 358,
    GroupNonUniformBitwiseAnd = 359,
    GroupNonUniformBitwiseOr = 360,
    GroupNonUniformBitwiseXor = 361,
    GroupNonUniformLogicalAnd = 362,
    GroupNonUniformLogicalOr = 363,
    GroupNonUniformLogicalXor = 364,
    GroupNonUniformQuadBroadcast = 365,
    GroupNonUniformQuadSwap = 366,
    CopyLogical = 400,
    PtrEqual = 401,
    PtrNotEqual = 402,
    PtrDiff = 403,
    ColorAttachmentReadEXT = 4160,
    DepthAttachmentReadEXT = 4161,
    StencilAttachmentReadEXT = 4162,
    TypeTensorARM = 4163,
    TensorReadARM = 4164,
    TensorWriteARM = 4165,
    TensorQuerySizeARM = 4166,
    GraphConstantARM = 4181,
    GraphEntryPointARM = 4182,
    GraphARM = 4183,
    GraphInputARM = 4184,
    GraphSetOutputARM = 4185,
    GraphEndARM = 4186,
    TypeGraphARM = 4190,
    TerminateInvocation = 4416,
    TypeUntypedPointerKHR = 4417,
    UntypedVariableKHR = 4418,
    UntypedAccessChainKHR = 4419,
    UntypedInBoundsAccessChainKHR = 4420,
    SubgroupBallotKHR = 4421,
    SubgroupFirstInvocationKHR = 4422,
    UntypedPtrAccessChainKHR = 4423,
    UntypedInBoundsPtrAccessChainKHR = 4424,
    UntypedArrayLengthKHR = 4425,
    UntypedPrefetchKHR = 4426,
    FmaKHR = 4427,
    SubgroupAllKHR = 4428,
    SubgroupAnyKHR = 4429,
    SubgroupAllEqualKHR = 4430,
    GroupNonUniformRotateKHR = 4431,
    SubgroupReadInvocationKHR = 4432,
    ExtInstWithForwardRefsKHR = 4433,
    UntypedGroupAsyncCopyKHR = 4434,
    TraceRayKHR = 4445,
    ExecuteCallableKHR = 4446,
    ConvertUToAccelerationStructureKHR = 4447,
    IgnoreIntersectionKHR = 4448,
    TerminateRayKHR = 4449,
    SDot = 4450,
    SDotKHR = 4450,
    UDot = 4451,
    UDotKHR = 4451,
    SUDot = 4452,
    SUDotKHR = 4452,
    SDotAccSat = 4453,
    SDotAccSatKHR = 4453,
    UDotAccSat = 4454,
    UDotAccSatKHR = 4454,
    SUDotAccSat = 4455,
    SUDotAccSatKHR = 4455,
    TypeCooperativeMatrixKHR = 4456,
    CooperativeMatrixLoadKHR = 4457,
    CooperativeMatrixStoreKHR = 4458,
    CooperativeMatrixMulAddKHR = 4459,
    CooperativeMatrixLengthKHR = 4460,
    ConstantCompositeReplicateEXT = 4461,
    SpecConstantCompositeReplicateEXT = 4462,
    CompositeConstructReplicateEXT = 4463,
    TypeRayQueryKHR = 4472,
    RayQueryInitializeKHR = 4473,
    RayQueryTerminateKHR = 4474,
    RayQueryGenerateIntersectionKHR = 4475,
    RayQueryConfirmIntersectionKHR = 4476,
    RayQueryProceedKHR = 4477,
    RayQueryGetIntersectionTypeKHR = 4479,
    ImageSampleWeightedQCOM = 4480,
    ImageBoxFilterQCOM = 4481,
    ImageBlockMatchSSDQCOM = 4482,
    ImageBlockMatchSADQCOM = 4483,
    BitCastArrayQCOM = 4497,
    ImageBlockMatchWindowSSDQCOM = 4500,
    ImageBlockMatchWindowSADQCOM = 4501,
    ImageBlockMatchGatherSSDQCOM = 4502,
    ImageBlockMatchGatherSADQCOM = 4503,
    CompositeConstructCoopMatQCOM = 4540,
    CompositeExtractCoopMatQCOM = 4541,
    ExtractSubArrayQCOM = 4542,
    GroupIAddNonUniformAMD = 5000,
    GroupFAddNonUniformAMD = 5001,
    GroupFMinNonUniformAMD = 5002,
    GroupUMinNonUniformAMD = 5003,
    GroupSMinNonUniformAMD = 5004,
    GroupFMaxNonUniformAMD = 5005,
    GroupUMaxNonUniformAMD = 5006,
    GroupSMaxNonUniformAMD = 5007,
    FragmentMaskFetchAMD = 5011,
    FragmentFetchAMD = 5012,
    ReadClockKHR = 5056,
    AllocateNodePayloadsAMDX = 5074,
    EnqueueNodePayloadsAMDX = 5075,
    TypeNodePayloadArrayAMDX = 5076,
    FinishWritingNodePayloadAMDX = 5078,
    NodePayloadArrayLengthAMDX = 5090,
    IsNodePayloadValidAMDX = 5101,
    ConstantStringAMDX = 5103,
    SpecConstantStringAMDX = 5104,
    GroupNonUniformQuadAllKHR = 5110,
    GroupNonUniformQuadAnyKHR = 5111,
    TypeBufferEXT = 5115,
    BufferPointerEXT = 5119,
    UntypedImageTexelPointerEXT = 5126,
    MemberDecorateIdEXT = 5127,
    ConstantSizeOfEXT = 5129,
    HitObjectRecordHitMotionNV = 5249,
    HitObjectRecordHitWithIndexMotionNV = 5250,
    HitObjectRecordMissMotionNV = 5251,
    HitObjectGetWorldToObjectNV = 5252,
    HitObjectGetObjectToWorldNV = 5253,
    HitObjectGetObjectRayDirectionNV = 5254,
    HitObjectGetObjectRayOriginNV = 5255,
    HitObjectTraceRayMotionNV = 5256,
    HitObjectGetShaderRecordBufferHandleNV = 5257,
    HitObjectGetShaderBindingTableRecordIndexNV = 5258,
    HitObjectRecordEmptyNV = 5259,
    HitObjectTraceRayNV = 5260,
    HitObjectRecordHitNV = 5261,
    HitObjectRecordHitWithIndexNV = 5262,
    HitObjectRecordMissNV = 5263,
    HitObjectExecuteShaderNV = 5264,
    HitObjectGetCurrentTimeNV = 5265,
    HitObjectGetAttributesNV = 5266,
    HitObjectGetHitKindNV = 5267,
    HitObjectGetPrimitiveIndexNV = 5268,
    HitObjectGetGeometryIndexNV = 5269,
    HitObjectGetInstanceIdNV = 5270,
    HitObjectGetInstanceCustomIndexNV = 5271,
    HitObjectGetWorldRayDirectionNV = 5272,
    HitObjectGetWorldRayOriginNV = 5273,
    HitObjectGetRayTMaxNV = 5274,
    HitObjectGetRayTMinNV = 5275,
    HitObjectIsEmptyNV = 5276,
    HitObjectIsHitNV = 5277,
    HitObjectIsMissNV = 5278,
    ReorderThreadWithHitObjectNV = 5279,
    ReorderThreadWithHintNV = 5280,
    TypeHitObjectNV = 5281,
    ImageSampleFootprintNV = 5283,
    TypeCooperativeVectorNV = 5288,
    TypeVectorIdEXT = 5288,
    CooperativeVectorMatrixMulNV = 5289,
    CooperativeVectorOuterProductAccumulateNV = 5290,
    CooperativeVectorReduceSumAccumulateNV = 5291,
    CooperativeVectorMatrixMulAddNV = 5292,
    CooperativeMatrixConvertNV = 5293,
    EmitMeshTasksEXT = 5294,
    SetMeshOutputsEXT = 5295,
    GroupNonUniformPartitionEXT = 5296,
    GroupNonUniformPartitionNV = 5296,
    WritePackedPrimitiveIndices4x8NV = 5299,
    FetchMicroTriangleVertexPositionNV = 5300,
    FetchMicroTriangleVertexBarycentricNV = 5301,
    CooperativeVectorLoadNV = 5302,
    CooperativeVectorStoreNV = 5303,
    HitObjectRecordFromQueryEXT = 5304,
    HitObjectRecordMissEXT = 5305,
    HitObjectRecordMissMotionEXT = 5306,
    HitObjectGetIntersectionTriangleVertexPositionsEXT = 5307,
    HitObjectGetRayFlagsEXT = 5308,
    HitObjectSetShaderBindingTableRecordIndexEXT = 5309,
    HitObjectReorderExecuteShaderEXT = 5310,
    HitObjectTraceReorderExecuteEXT = 5311,
    HitObjectTraceMotionReorderExecuteEXT = 5312,
    TypeHitObjectEXT = 5313,
    ReorderThreadWithHintEXT = 5314,
    ReorderThreadWithHitObjectEXT = 5315,
    HitObjectTraceRayEXT = 5316,
    HitObjectTraceRayMotionEXT = 5317,
    HitObjectRecordEmptyEXT = 5318,
    HitObjectExecuteShaderEXT = 5319,
    HitObjectGetCurrentTimeEXT = 5320,
    HitObjectGetAttributesEXT = 5321,
    HitObjectGetHitKindEXT = 5322,
    HitObjectGetPrimitiveIndexEXT = 5323,
    HitObjectGetGeometryIndexEXT = 5324,
    HitObjectGetInstanceIdEXT = 5325,
    HitObjectGetInstanceCustomIndexEXT = 5326,
    HitObjectGetObjectRayOriginEXT = 5327,
    HitObjectGetObjectRayDirectionEXT = 5328,
    HitObjectGetWorldRayDirectionEXT = 5329,
    HitObjectGetWorldRayOriginEXT = 5330,
    HitObjectGetObjectToWorldEXT = 5331,
    HitObjectGetWorldToObjectEXT = 5332,
    HitObjectGetRayTMaxEXT = 5333,
    ReportIntersectionKHR = 5334,
    ReportIntersectionNV = 5334,
    IgnoreIntersectionNV = 5335,
    TerminateRayNV = 5336,
    TraceNV = 5337,
    TraceMotionNV = 5338,
    TraceRayMotionNV = 5339,
    RayQueryGetIntersectionTriangleVertexPositionsKHR = 5340,
    TypeAccelerationStructureKHR = 5341,
    TypeAccelerationStructureNV = 5341,
    ExecuteCallableNV = 5344,
    RayQueryGetClusterIdNV = 5345,
    RayQueryGetIntersectionClusterIdNV = 5345,
    HitObjectGetClusterIdNV = 5346,
    HitObjectGetRayTMinEXT = 5347,
    HitObjectGetShaderBindingTableRecordIndexEXT = 5348,
    HitObjectGetShaderRecordBufferHandleEXT = 5349,
    HitObjectIsEmptyEXT = 5350,
    HitObjectIsHitEXT = 5351,
    HitObjectIsMissEXT = 5352,
    TypeCooperativeMatrixNV = 5358,
    CooperativeMatrixLoadNV = 5359,
    CooperativeMatrixStoreNV = 5360,
    CooperativeMatrixMulAddNV = 5361,
    CooperativeMatrixLengthNV = 5362,
    BeginInvocationInterlockEXT = 5364,
    EndInvocationInterlockEXT = 5365,
    CooperativeMatrixReduceNV = 5366,
    CooperativeMatrixLoadTensorNV = 5367,
    CooperativeMatrixStoreTensorNV = 5368,
    CooperativeMatrixPerElementOpNV = 5369,
    TypeTensorLayoutNV = 5370,
    TypeTensorViewNV = 5371,
    CreateTensorLayoutNV = 5372,
    TensorLayoutSetDimensionNV = 5373,
    TensorLayoutSetStrideNV = 5374,
    TensorLayoutSliceNV = 5375,
    TensorLayoutSetClampValueNV = 5376,
    CreateTensorViewNV = 5377,
    TensorViewSetDimensionNV = 5378,
    TensorViewSetStrideNV = 5379,
    DemoteToHelperInvocation = 5380,
    DemoteToHelperInvocationEXT = 5380,
    IsHelperInvocationEXT = 5381,
    TensorViewSetClipNV = 5382,
    TensorLayoutSetBlockSizeNV = 5384,
    CooperativeMatrixTransposeNV = 5390,
    ConvertUToImageNV = 5391,
    ConvertUToSamplerNV = 5392,
    ConvertImageToUNV = 5393,
    ConvertSamplerToUNV = 5394,
    ConvertUToSampledImageNV = 5395,
    ConvertSampledImageToUNV = 5396,
    SamplerImageAddressingModeNV = 5397,
    RawAccessChainNV = 5398,
    RayQueryGetIntersectionSpherePositionNV = 5427,
    RayQueryGetIntersectionSphereRadiusNV = 5428,
    RayQueryGetIntersectionLSSPositionsNV = 5429,
    RayQueryGetIntersectionLSSRadiiNV = 5430,
    RayQueryGetIntersectionLSSHitValueNV = 5431,
    HitObjectGetSpherePositionNV = 5432,
    HitObjectGetSphereRadiusNV = 5433,
    HitObjectGetLSSPositionsNV = 5434,
    HitObjectGetLSSRadiiNV = 5435,
    HitObjectIsSphereHitNV = 5436,
    HitObjectIsLSSHitNV = 5437,
    RayQueryIsSphereHitNV = 5438,
    RayQueryIsLSSHitNV = 5439,
    SubgroupShuffleINTEL = 5571,
    SubgroupShuffleDownINTEL = 5572,
    SubgroupShuffleUpINTEL = 5573,
    SubgroupShuffleXorINTEL = 5574,
    SubgroupBlockReadINTEL = 5575,
    SubgroupBlockWriteINTEL = 5576,
    SubgroupImageBlockReadINTEL = 5577,
    SubgroupImageBlockWriteINTEL = 5578,
    SubgroupImageMediaBlockReadINTEL = 5580,
    SubgroupImageMediaBlockWriteINTEL = 5581,
    UCountLeadingZerosINTEL = 5585,
    UCountTrailingZerosINTEL = 5586,
    AbsISubINTEL = 5587,
    AbsUSubINTEL = 5588,
    IAddSatINTEL = 5589,
    UAddSatINTEL = 5590,
    IAverageINTEL = 5591,
    UAverageINTEL = 5592,
    IAverageRoundedINTEL = 5593,
    UAverageRoundedINTEL = 5594,
    ISubSatINTEL = 5595,
    USubSatINTEL = 5596,
    IMul32x16INTEL = 5597,
    UMul32x16INTEL = 5598,
    ConstantFunctionPointerINTEL = 5600,
    FunctionPointerCallINTEL = 5601,
    AsmTargetINTEL = 5609,
    AsmINTEL = 5610,
    AsmCallINTEL = 5611,
    AtomicFMinEXT = 5614,
    AtomicFMaxEXT = 5615,
    AssumeTrueKHR = 5630,
    ExpectKHR = 5631,
    DecorateString = 5632,
    DecorateStringGOOGLE = 5632,
    MemberDecorateString = 5633,
    MemberDecorateStringGOOGLE = 5633,
    VmeImageINTEL = 5699,
    TypeVmeImageINTEL = 5700,
    TypeAvcImePayloadINTEL = 5701,
    TypeAvcRefPayloadINTEL = 5702,
    TypeAvcSicPayloadINTEL = 5703,
    TypeAvcMcePayloadINTEL = 5704,
    TypeAvcMceResultINTEL = 5705,
    TypeAvcImeResultINTEL = 5706,
    TypeAvcImeResultSingleReferenceStreamoutINTEL = 5707,
    TypeAvcImeResultDualReferenceStreamoutINTEL = 5708,
    TypeAvcImeSingleReferenceStreaminINTEL = 5709,
    TypeAvcImeDualReferenceStreaminINTEL = 5710,
    TypeAvcRefResultINTEL = 5711,
    TypeAvcSicResultINTEL = 5712,
    SubgroupAvcMceGetDefaultInterBaseMultiReferencePenaltyINTEL = 5713,
    SubgroupAvcMceSetInterBaseMultiReferencePenaltyINTEL = 5714,
    SubgroupAvcMceGetDefaultInterShapePenaltyINTEL = 5715,
    SubgroupAvcMceSetInterShapePenaltyINTEL = 5716,
    SubgroupAvcMceGetDefaultInterDirectionPenaltyINTEL = 5717,
    SubgroupAvcMceSetInterDirectionPenaltyINTEL = 5718,
    SubgroupAvcMceGetDefaultIntraLumaShapePenaltyINTEL = 5719,
    SubgroupAvcMceGetDefaultInterMotionVectorCostTableINTEL = 5720,
    SubgroupAvcMceGetDefaultHighPenaltyCostTableINTEL = 5721,
    SubgroupAvcMceGetDefaultMediumPenaltyCostTableINTEL = 5722,
    SubgroupAvcMceGetDefaultLowPenaltyCostTableINTEL = 5723,
    SubgroupAvcMceSetMotionVectorCostFunctionINTEL = 5724,
    SubgroupAvcMceGetDefaultIntraLumaModePenaltyINTEL = 5725,
    SubgroupAvcMceGetDefaultNonDcLumaIntraPenaltyINTEL = 5726,
    SubgroupAvcMceGetDefaultIntraChromaModeBasePenaltyINTEL = 5727,
    SubgroupAvcMceSetAcOnlyHaarINTEL = 5728,
    SubgroupAvcMceSetSourceInterlacedFieldPolarityINTEL = 5729,
    SubgroupAvcMceSetSingleReferenceInterlacedFieldPolarityINTEL = 5730,
    SubgroupAvcMceSetDualReferenceInterlacedFieldPolaritiesINTEL = 5731,
    SubgroupAvcMceConvertToImePayloadINTEL = 5732,
    SubgroupAvcMceConvertToImeResultINTEL = 5733,
    SubgroupAvcMceConvertToRefPayloadINTEL = 5734,
    SubgroupAvcMceConvertToRefResultINTEL = 5735,
    SubgroupAvcMceConvertToSicPayloadINTEL = 5736,
    SubgroupAvcMceConvertToSicResultINTEL = 5737,
    SubgroupAvcMceGetMotionVectorsINTEL = 5738,
    SubgroupAvcMceGetInterDistortionsINTEL = 5739,
    SubgroupAvcMceGetBestInterDistortionsINTEL = 5740,
    SubgroupAvcMceGetInterMajorShapeINTEL = 5741,
    SubgroupAvcMceGetInterMinorShapeINTEL = 5742,
    SubgroupAvcMceGetInterDirectionsINTEL = 5743,
    SubgroupAvcMceGetInterMotionVectorCountINTEL = 5744,
    SubgroupAvcMceGetInterReferenceIdsINTEL = 5745,
    SubgroupAvcMceGetInterReferenceInterlacedFieldPolaritiesINTEL = 5746,
    SubgroupAvcImeInitializeINTEL = 5747,
    SubgroupAvcImeSetSingleReferenceINTEL = 5748,
    SubgroupAvcImeSetDualReferenceINTEL = 5749,
    SubgroupAvcImeRefWindowSizeINTEL = 5750,
    SubgroupAvcImeAdjustRefOffsetINTEL = 5751,
    SubgroupAvcImeConvertToMcePayloadINTEL = 5752,
    SubgroupAvcImeSetMaxMotionVectorCountINTEL = 5753,
    SubgroupAvcImeSetUnidirectionalMixDisableINTEL = 5754,
    SubgroupAvcImeSetEarlySearchTerminationThresholdINTEL = 5755,
    SubgroupAvcImeSetWeightedSadINTEL = 5756,
    SubgroupAvcImeEvaluateWithSingleReferenceINTEL = 5757,
    SubgroupAvcImeEvaluateWithDualReferenceINTEL = 5758,
    SubgroupAvcImeEvaluateWithSingleReferenceStreaminINTEL = 5759,
    SubgroupAvcImeEvaluateWithDualReferenceStreaminINTEL = 5760,
    SubgroupAvcImeEvaluateWithSingleReferenceStreamoutINTEL = 5761,
    SubgroupAvcImeEvaluateWithDualReferenceStreamoutINTEL = 5762,
    SubgroupAvcImeEvaluateWithSingleReferenceStreaminoutINTEL = 5763,
    SubgroupAvcImeEvaluateWithDualReferenceStreaminoutINTEL = 5764,
    SubgroupAvcImeConvertToMceResultINTEL = 5765,
    SubgroupAvcImeGetSingleReferenceStreaminINTEL = 5766,
    SubgroupAvcImeGetDualReferenceStreaminINTEL = 5767,
    SubgroupAvcImeStripSingleReferenceStreamoutINTEL = 5768,
    SubgroupAvcImeStripDualReferenceStreamoutINTEL = 5769,
    SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeMotionVectorsINTEL = 5770,
    SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeDistortionsINTEL = 5771,
    SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeReferenceIdsINTEL = 5772,
    SubgroupAvcImeGetStreamoutDualReferenceMajorShapeMotionVectorsINTEL = 5773,
    SubgroupAvcImeGetStreamoutDualReferenceMajorShapeDistortionsINTEL = 5774,
    SubgroupAvcImeGetStreamoutDualReferenceMajorShapeReferenceIdsINTEL = 5775,
    SubgroupAvcImeGetBorderReachedINTEL = 5776,
    SubgroupAvcImeGetTruncatedSearchIndicationINTEL = 5777,
    SubgroupAvcImeGetUnidirectionalEarlySearchTerminationINTEL = 5778,
    SubgroupAvcImeGetWeightingPatternMinimumMotionVectorINTEL = 5779,
    SubgroupAvcImeGetWeightingPatternMinimumDistortionINTEL = 5780,
    SubgroupAvcFmeInitializeINTEL = 5781,
    SubgroupAvcBmeInitializeINTEL = 5782,
    SubgroupAvcRefConvertToMcePayloadINTEL = 5783,
    SubgroupAvcRefSetBidirectionalMixDisableINTEL = 5784,
    SubgroupAvcRefSetBilinearFilterEnableINTEL = 5785,
    SubgroupAvcRefEvaluateWithSingleReferenceINTEL = 5786,
    SubgroupAvcRefEvaluateWithDualReferenceINTEL = 5787,
    SubgroupAvcRefEvaluateWithMultiReferenceINTEL = 5788,
    SubgroupAvcRefEvaluateWithMultiReferenceInterlacedINTEL = 5789,
    SubgroupAvcRefConvertToMceResultINTEL = 5790,
    SubgroupAvcSicInitializeINTEL = 5791,
    SubgroupAvcSicConfigureSkcINTEL = 5792,
    SubgroupAvcSicConfigureIpeLumaINTEL = 5793,
    SubgroupAvcSicConfigureIpeLumaChromaINTEL = 5794,
    SubgroupAvcSicGetMotionVectorMaskINTEL = 5795,
    SubgroupAvcSicConvertToMcePayloadINTEL = 5796,
    SubgroupAvcSicSetIntraLumaShapePenaltyINTEL = 5797,
    SubgroupAvcSicSetIntraLumaModeCostFunctionINTEL = 5798,
    SubgroupAvcSicSetIntraChromaModeCostFunctionINTEL = 5799,
    SubgroupAvcSicSetBilinearFilterEnableINTEL = 5800,
    SubgroupAvcSicSetSkcForwardTransformEnableINTEL = 5801,
    SubgroupAvcSicSetBlockBasedRawSkipSadINTEL = 5802,
    SubgroupAvcSicEvaluateIpeINTEL = 5803,
    SubgroupAvcSicEvaluateWithSingleReferenceINTEL = 5804,
    SubgroupAvcSicEvaluateWithDualReferenceINTEL = 5805,
    SubgroupAvcSicEvaluateWithMultiReferenceINTEL = 5806,
    SubgroupAvcSicEvaluateWithMultiReferenceInterlacedINTEL = 5807,
    SubgroupAvcSicConvertToMceResultINTEL = 5808,
    SubgroupAvcSicGetIpeLumaShapeINTEL = 5809,
    SubgroupAvcSicGetBestIpeLumaDistortionINTEL = 5810,
    SubgroupAvcSicGetBestIpeChromaDistortionINTEL = 5811,
    SubgroupAvcSicGetPackedIpeLumaModesINTEL = 5812,
    SubgroupAvcSicGetIpeChromaModeINTEL = 5813,
    SubgroupAvcSicGetPackedSkcLumaCountThresholdINTEL = 5814,
    SubgroupAvcSicGetPackedSkcLumaSumThresholdINTEL = 5815,
    SubgroupAvcSicGetInterRawSadsINTEL = 5816,
    VariableLengthArrayINTEL = 5818,
    SaveMemoryINTEL = 5819,
    RestoreMemoryINTEL = 5820,
    ArbitraryFloatSinCosPiALTERA = 5840,
    ArbitraryFloatSinCosPiINTEL = 5840,
    ArbitraryFloatCastALTERA = 5841,
    ArbitraryFloatCastINTEL = 5841,
    ArbitraryFloatCastFromIntALTERA = 5842,
    ArbitraryFloatCastFromIntINTEL = 5842,
    ArbitraryFloatCastToIntALTERA = 5843,
    ArbitraryFloatCastToIntINTEL = 5843,
    ArbitraryFloatAddALTERA = 5846,
    ArbitraryFloatAddINTEL = 5846,
    ArbitraryFloatSubALTERA = 5847,
    ArbitraryFloatSubINTEL = 5847,
    ArbitraryFloatMulALTERA = 5848,
    ArbitraryFloatMulINTEL = 5848,
    ArbitraryFloatDivALTERA = 5849,
    ArbitraryFloatDivINTEL = 5849,
    ArbitraryFloatGTALTERA = 5850,
    ArbitraryFloatGTINTEL = 5850,
    ArbitraryFloatGEALTERA = 5851,
    ArbitraryFloatGEINTEL = 5851,
    ArbitraryFloatLTALTERA = 5852,
    ArbitraryFloatLTINTEL = 5852,
    ArbitraryFloatLEALTERA = 5853,
    ArbitraryFloatLEINTEL = 5853,
    ArbitraryFloatEQALTERA = 5854,
    ArbitraryFloatEQINTEL = 5854,
    ArbitraryFloatRecipALTERA = 5855,
    ArbitraryFloatRecipINTEL = 5855,
    ArbitraryFloatRSqrtALTERA = 5856,
    ArbitraryFloatRSqrtINTEL = 5856,
    ArbitraryFloatCbrtALTERA = 5857,
    ArbitraryFloatCbrtINTEL = 5857,
    ArbitraryFloatHypotALTERA = 5858,
    ArbitraryFloatHypotINTEL = 5858,
    ArbitraryFloatSqrtALTERA = 5859,
    ArbitraryFloatSqrtINTEL = 5859,
    ArbitraryFloatLogINTEL = 5860,
    ArbitraryFloatLog2INTEL = 5861,
    ArbitraryFloatLog10INTEL = 5862,
    ArbitraryFloatLog1pINTEL = 5863,
    ArbitraryFloatExpINTEL = 5864,
    ArbitraryFloatExp2INTEL = 5865,
    ArbitraryFloatExp10INTEL = 5866,
    ArbitraryFloatExpm1INTEL = 5867,
    ArbitraryFloatSinINTEL = 5868,
    ArbitraryFloatCosINTEL = 5869,
    ArbitraryFloatSinCosINTEL = 5870,
    ArbitraryFloatSinPiINTEL = 5871,
    ArbitraryFloatCosPiINTEL = 5872,
    ArbitraryFloatASinINTEL = 5873,
    ArbitraryFloatASinPiINTEL = 5874,
    ArbitraryFloatACosINTEL = 5875,
    ArbitraryFloatACosPiINTEL = 5876,
    ArbitraryFloatATanINTEL = 5877,
    ArbitraryFloatATanPiINTEL = 5878,
    ArbitraryFloatATan2INTEL = 5879,
    ArbitraryFloatPowINTEL = 5880,
    ArbitraryFloatPowRINTEL = 5881,
    ArbitraryFloatPowNINTEL = 5882,
    LoopControlINTEL = 5887,
    AliasDomainDeclINTEL = 5911,
    AliasScopeDeclINTEL = 5912,
    AliasScopeListDeclINTEL = 5913,
    FixedSqrtALTERA = 5923,
    FixedSqrtINTEL = 5923,
    FixedRecipALTERA = 5924,
    FixedRecipINTEL = 5924,
    FixedRsqrtALTERA = 5925,
    FixedRsqrtINTEL = 5925,
    FixedSinALTERA = 5926,
    FixedSinINTEL = 5926,
    FixedCosALTERA = 5927,
    FixedCosINTEL = 5927,
    FixedSinCosALTERA = 5928,
    FixedSinCosINTEL = 5928,
    FixedSinPiALTERA = 5929,
    FixedSinPiINTEL = 5929,
    FixedCosPiALTERA = 5930,
    FixedCosPiINTEL = 5930,
    FixedSinCosPiALTERA = 5931,
    FixedSinCosPiINTEL = 5931,
    FixedLogALTERA = 5932,
    FixedLogINTEL = 5932,
    FixedExpALTERA = 5933,
    FixedExpINTEL = 5933,
    PtrCastToCrossWorkgroupALTERA = 5934,
    PtrCastToCrossWorkgroupINTEL = 5934,
    CrossWorkgroupCastToPtrALTERA = 5938,
    CrossWorkgroupCastToPtrINTEL = 5938,
    ReadPipeBlockingALTERA = 5946,
    ReadPipeBlockingINTEL = 5946,
    WritePipeBlockingALTERA = 5947,
    WritePipeBlockingINTEL = 5947,
    FPGARegALTERA = 5949,
    FPGARegINTEL = 5949,
    RayQueryGetRayTMinKHR = 6016,
    RayQueryGetRayFlagsKHR = 6017,
    RayQueryGetIntersectionTKHR = 6018,
    RayQueryGetIntersectionInstanceCustomIndexKHR = 6019,
    RayQueryGetIntersectionInstanceIdKHR = 6020,
    RayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetKHR = 6021,
    RayQueryGetIntersectionGeometryIndexKHR = 6022,
    RayQueryGetIntersectionPrimitiveIndexKHR = 6023,
    RayQueryGetIntersectionBarycentricsKHR = 6024,
    RayQueryGetIntersectionFrontFaceKHR = 6025,
    RayQueryGetIntersectionCandidateAABBOpaqueKHR = 6026,
    RayQueryGetIntersectionObjectRayDirectionKHR = 6027,
    RayQueryGetIntersectionObjectRayOriginKHR = 6028,
    RayQueryGetWorldRayDirectionKHR = 6029,
    RayQueryGetWorldRayOriginKHR = 6030,
    RayQueryGetIntersectionObjectToWorldKHR = 6031,
    RayQueryGetIntersectionWorldToObjectKHR = 6032,
    AtomicFAddEXT = 6035,
    TypeBufferSurfaceINTEL = 6086,
    TypeStructContinuedINTEL = 6090,
    ConstantCompositeContinuedINTEL = 6091,
    SpecConstantCompositeContinuedINTEL = 6092,
    CompositeConstructContinuedINTEL = 6096,
    ConvertFToBF16INTEL = 6116,
    ConvertBF16ToFINTEL = 6117,
    ControlBarrierArriveINTEL = 6142,
    ControlBarrierWaitINTEL = 6143,
    ArithmeticFenceEXT = 6145,
    TaskSequenceCreateALTERA = 6163,
    TaskSequenceCreateINTEL = 6163,
    TaskSequenceAsyncALTERA = 6164,
    TaskSequenceAsyncINTEL = 6164,
    TaskSequenceGetALTERA = 6165,
    TaskSequenceGetINTEL = 6165,
    TaskSequenceReleaseALTERA = 6166,
    TaskSequenceReleaseINTEL = 6166,
    TypeTaskSequenceALTERA = 6199,
    TypeTaskSequenceINTEL = 6199,
    SubgroupBlockPrefetchINTEL = 6221,
    Subgroup2DBlockLoadINTEL = 6231,
    Subgroup2DBlockLoadTransformINTEL = 6232,
    Subgroup2DBlockLoadTransposeINTEL = 6233,
    Subgroup2DBlockPrefetchINTEL = 6234,
    Subgroup2DBlockStoreINTEL = 6235,
    SubgroupMatrixMultiplyAccumulateINTEL = 6237,
    BitwiseFunctionINTEL = 6242,
    UntypedVariableLengthArrayINTEL = 6244,
    ConditionalExtensionINTEL = 6248,
    ConditionalEntryPointINTEL = 6249,
    ConditionalCapabilityINTEL = 6250,
    SpecConstantTargetINTEL = 6251,
    SpecConstantArchitectureINTEL = 6252,
    SpecConstantCapabilitiesINTEL = 6253,
    ConditionalCopyObjectINTEL = 6254,
    GroupIMulKHR = 6401,
    GroupFMulKHR = 6402,
    GroupBitwiseAndKHR = 6403,
    GroupBitwiseOrKHR = 6404,
    GroupBitwiseXorKHR = 6405,
    GroupLogicalAndKHR = 6406,
    GroupLogicalOrKHR = 6407,
    GroupLogicalXorKHR = 6408,
    RoundFToTF32INTEL = 6426,
    MaskedGatherINTEL = 6428,
    MaskedScatterINTEL = 6429,
    ConvertHandleToImageINTEL = 6529,
    ConvertHandleToSamplerINTEL = 6530,
    ConvertHandleToSampledImageINTEL = 6531,
    Max = 0x7fffffff,
};

enum class spv_op_process_result
{
    Ok,
    InvalidState,
    MakeNop,
};

#if 0
void Init(spv_shader &self, span<uint32_t> data, RhiShaderStage expectedStage)
{
    SpvReader::ReadHeader(data);
    while (data.size)
    {
        span<uint32_t> opWithOperands = SpvReader::ReadOpWithOperands(data);
        switch (SpirvReader::ParseOp(Span::Front(opWithOperands)))
        {

#define X(name)                                                                                                        \
    case spv::name: {                                                                                                  \
        name(it);                                                                                                      \
        break;                                                                                                         \
    }
            X(OpEntryPoint)
            X(OpExtension)
            X(OpDecorate)
            X(OpDecorateString)
            X(OpVariable)
        }
    }
}
#endif

#if 0
auto FindLocationBySemantic(Str semantic, StorageClass storageClass, uint32_t *outLocation) -> bool
{
    uint32_t id;
    if (!FindIdBySemantic(semantic, storageClass, &id))
        return false;

    uint32_t location;
    for (uint32_t i = 0; i < m_Locations.Size(); ++i)
    {
        if (m_Locations[i].id == id && CheckStorageClass(id, storageClass))
        {
            *outLocation = m_Locations[i].location;
            return true;
        }
    }

    return false;
}

auto FindIdBySemantic(Str querySemantic, StorageClass storageClass, uint32_t *outId) -> bool
{
    for (uint32_t i = 0; i < m_SemanticDataNames.Size(); ++i)
    {
        const auto &semantic = m_SemanticDataNames[i];
        if (semantic == querySemantic && CheckStorageClass(m_SemanticDataIds[i], storageClass))
        {
            *outId = m_SemanticDataIds[i];
            return true;
        }
    }
    return false;
}

auto FindSemanticById(uint32_t id, Str *outSemantic) -> bool
{
    for (uint32_t i = 0; i < m_SemanticDataIds.Size(); ++i)
    {
        if (m_SemanticDataIds[i] == id)
        {
            *outSemantic = m_SemanticDataNames[i].GetStr();
            return true;
        }
    }
    return false;
}

auto RewriteLocationForSemantic(Str semantic, StorageClass storageClass, uint32_t aLocation) -> bool
{
    uint32_t oldLocation;
    if (!FindLocationBySemantic(semantic, storageClass, &oldLocation))
        return false;

    if (oldLocation == aLocation)
        return true;

    auto end = m_SpvView.end();
    for (auto it = m_SpvView.begin(); it != end; ++it)
    {
        auto op = spv::Op(it.Op());

        if (op != spv::OpDecorate)
            continue;

        SpvOperandReader operandReader = it.GetOperandReader();

        uint32_t id = operandReader.Word();

        if (spv::Decoration(operandReader.Word()) != spv::DecorationLocation)
            continue;
        if (!CheckStorageClass(id, storageClass))
            continue;

        uint32_t &location = operandReader.Word();
        if (location == oldLocation)
        {
            location = aLocation;
            return true;
        }
    }

    return false;
}
#endif

namespace
{

auto HandleOpEntryPoint(spv_shader &self, span<uint32_t> operands) -> spv_op_process_result
{
    auto executionModel = (spv_execution_model)SpvReader::ReadWord(operands);
    switch (executionModel)
    {
    case spv_execution_model::Vertex: {
        if (self.stage == RhiShaderStage::Vertex)
            return spv_op_process_result::Ok;

        return spv_op_process_result::InvalidState;
    }

    case spv_execution_model::Fragment: {
        if (self.stage == RhiShaderStage::Pixel)
            return spv_op_process_result::Ok;

        return spv_op_process_result::InvalidState;
    }

    default:
        return spv_op_process_result::InvalidState;
    }
}

auto HandleOpExtension(spv_shader &self, span<uint32_t> operands) -> spv_op_process_result
{
    byteview name = SpvReader::ReadString(operands);
    if (Span::Eq(name, "SPV_GOOGLE_hlsl_functionality1"_s))
        return spv_op_process_result::MakeNop;
    if (Span::Eq(name, "SPV_GOOGLE_user_type"_s))
        return spv_op_process_result::MakeNop;

    return spv_op_process_result::Ok;
}

auto HandleOpDecorate(spv_shader &self, span<uint32_t> operands) -> spv_op_process_result
{
    uint32_t targetId = SpvReader::ReadWord(operands);

    switch ((spv_decoration)SpvReader::ReadWord(operands))
    {
    case spv_decoration::Location: {
        const uint32_t location = SpvReader::ReadWord(operands);
        InlineVec::Append(self.locations, spv_shader::location_data{
                                              .id = targetId,
                                              .location = location,
                                          });
        return spv_op_process_result::Ok;
    }

    case spv_decoration::BuiltIn: {
        const uint32_t builtin = SpvReader::ReadWord(operands);
        InlineVec::Append(self.builtins, spv_shader::builtin_data{
                                             .id = targetId,
                                             .builtin = builtin,
                                         });
        return spv_op_process_result::Ok;
    }

    default: {
        return spv_op_process_result::Ok;
    }
    }
}

auto HandleOpDecorateString(spv_shader &self, span<uint32_t> operands) -> spv_op_process_result
{
    uint32_t targetId = SpvReader::ReadWord(operands);

    switch ((spv_decoration)SpvReader::ReadWord(operands))
    {
    case spv_decoration::UserSemantic: {
        InlineVec::Append(self.semanticDataIds, targetId);

        inline_string<16> &name = InlineVec::Append(self.semanticDataNames);
        byteview src = SpvReader::ReadString(operands);
        MemCpy(name.data.data, src.data, src.size);

        InlineString::AsciiToUpper(name);

        NYLA_LOG("" NYLA_SV_FMT, NYLA_SV_ARG((byteview)name));
        return spv_op_process_result::Ok;
    }

    default: {
        return spv_op_process_result::MakeNop;
    }
    }
}

auto HandleOpVariable(spv_shader &self, span<uint32_t> operands) -> spv_op_process_result
{
    uint32_t resultType = SpvReader::ReadWord(operands);
    uint32_t resultId = SpvReader::ReadWord(operands);

    switch ((spv_storage_class)SpvReader::ReadWord(operands))
    {
    case spv_storage_class::Input: {
        InlineVec::Append(self.inputVariables, resultId);
        return spv_op_process_result::Ok;
    }
    case spv_storage_class::Output: {
        InlineVec::Append(self.outputVariables, resultId);
        return spv_op_process_result::Ok;
    }
    default:
        return spv_op_process_result::Ok;
    }
}

} // namespace

} // namespace SpvShader

} // namespace nyla